//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billapong.MapEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Billapong.MapEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add holes here, please activate the game window first.
        /// </summary>
        public static string CannotAddHoles {
            get {
                return ResourceManager.GetString("CannotAddHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new map.
        /// </summary>
        public static string CreateNewMap {
            get {
                return ResourceManager.GetString("CreateNewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the map &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteMapQuestion {
            get {
                return ResourceManager.GetString("DeleteMapQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holes.
        /// </summary>
        public static string Holes {
            get {
                return ResourceManager.GetString("Holes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsPlayable {
            get {
                return ResourceManager.GetString("IsPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading maps, please wait....
        /// </summary>
        public static string LoadingMaps {
            get {
                return ResourceManager.GetString("LoadingMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billapong - Map Editor - Edit Map.
        /// </summary>
        public static string MapEditTitle {
            get {
                return ResourceManager.GetString("MapEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map is currently not valid. Please verify the following rules:{0}{0}- You have at least one active window{0}- Each window must be connected to another window{0}- You have at least one hole.
        /// </summary>
        public static string MapIsNotPlayable {
            get {
                return ResourceManager.GetString("MapIsNotPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map does not exist anymore!.
        /// </summary>
        public static string MapNotExist {
            get {
                return ResourceManager.GetString("MapNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billapong - Map Editor - Map Selection.
        /// </summary>
        public static string MapSelectionTitle {
            get {
                return ResourceManager.GetString("MapSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Windows.
        /// </summary>
        public static string MapWindows {
            get {
                return ResourceManager.GetString("MapWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameDoublePoint {
            get {
                return ResourceManager.GetString("NameDoublePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playable.
        /// </summary>
        public static string Playable {
            get {
                return ResourceManager.GetString("Playable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string RefreshList {
            get {
                return ResourceManager.GetString("RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Mode:.
        /// </summary>
        public static string SelectionModeDoublePoint {
            get {
                return ResourceManager.GetString("SelectionModeDoublePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is currently not available. Please start the server and restart the map editor..
        /// </summary>
        public static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings:.
        /// </summary>
        public static string SettingsDoublePoint {
            get {
                return ResourceManager.GetString("SettingsDoublePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Holes.
        /// </summary>
        public static string WindowHoles {
            get {
                return ResourceManager.GetString("WindowHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
    }
}
