//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billapong.GameConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Billapong.GameConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billapong.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to menu.
        /// </summary>
        public static string BackToMenu {
            get {
                return ResourceManager.GetString("BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel game.
        /// </summary>
        public static string CancelGame {
            get {
                return ResourceManager.GetString("CancelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is already opened!.
        /// </summary>
        public static string GameAlreadyOpened {
            get {
                return ResourceManager.GetString("GameAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended. Draw!.
        /// </summary>
        public static string GameDrawMessage {
            get {
                return ResourceManager.GetString("GameDrawMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game got canceled.
        /// </summary>
        public static string GameGotCanceled {
            get {
                return ResourceManager.GetString("GameGotCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended. You lost :(.
        /// </summary>
        public static string GameLostMessage {
            get {
                return ResourceManager.GetString("GameLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended. You won! :).
        /// </summary>
        public static string GameWonMessage {
            get {
                return ResourceManager.GetString("GameWonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join game.
        /// </summary>
        public static string JoinGame {
            get {
                return ResourceManager.GetString("JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining game. Please wait....
        /// </summary>
        public static string JoiningGameMessage {
            get {
                return ResourceManager.GetString("JoiningGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join multiplayer game.
        /// </summary>
        public static string JoinMultiPlayerGame {
            get {
                return ResourceManager.GetString("JoinMultiPlayerGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map editor.
        /// </summary>
        public static string MapEditor {
            get {
                return ResourceManager.GetString("MapEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maps found.
        /// </summary>
        public static string NoMapsFound {
            get {
                return ResourceManager.GetString("NoMapsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No open games found.
        /// </summary>
        public static string NoOpenGamesFound {
            get {
                return ResourceManager.GetString("NoOpenGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for maps....
        /// </summary>
        public static string SearchMaps {
            get {
                return ResourceManager.GetString("SearchMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for open games....
        /// </summary>
        public static string SearchOpenGames {
            get {
                return ResourceManager.GetString("SearchOpenGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start multiplayer game.
        /// </summary>
        public static string StartMultiPlayerGame {
            get {
                return ResourceManager.GetString("StartMultiPlayerGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start singleplayer game.
        /// </summary>
        public static string StartSinglePlayerGame {
            get {
                return ResourceManager.GetString("StartSinglePlayerGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start singleplayer training.
        /// </summary>
        public static string StartSinglePlayerTraining {
            get {
                return ResourceManager.GetString("StartSinglePlayerTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured. The game will now cancel.
        /// </summary>
        public static string UnexpectedGameError {
            get {
                return ResourceManager.GetString("UnexpectedGameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for opponent....
        /// </summary>
        public static string WaitingForOpponent {
            get {
                return ResourceManager.GetString("WaitingForOpponent", resourceCulture);
            }
        }
    }
}
